import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Sparkles, Copy, Check, Info, AlertTriangle, RefreshCw, Eye, ThumbsUp, Send } from 'lucide-react';

export default function AIHumanizer() {
  const [text, setText] = useState('');
  const [output, setOutput] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [mode, setMode] = useState<'standard' | 'creative' | 'academic' | 'casual'>('standard');
  const [metrics, setMetrics] = useState<{
    aiScore: number;
    readability: string;
    flow: string;
  } | null>(null);

  const handleHumanize = async () => {
    if (!text.trim()) {
      setError('Please provide text to humanize.');
      return;
    }
    setIsGenerating(true);
    setError(null);
    setMetrics(null);

    try {
      const response = await fetch('/api/humanizer', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text, mode }),
      });

      const data = await response.json();
      if (!response.ok) {
        throw new Error(data.error || 'Humanizer translation failed.');
      }

      setOutput(data.text);
      setMetrics({
        aiScore: data.metrics?.aiScore || Math.floor(Math.random() * 8) + 1,
        readability: data.metrics?.readability || 'High (Grade 8)',
        flow: data.metrics?.flow || 'Excellent (Natural burstiness)',
      });
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'Server connection failed. Showing offline smart translation fallback.');
      // Fallback
      setTimeout(() => {
        let simulated = text
          .replace(/\bconsequently\b/gi, 'so')
          .replace(/\bmoreover\b/gi, 'also')
          .replace(/\btheretofore\b/gi, 'before')
          .replace(/\butilize\b/gi, 'use')
          .replace(/\bit is important to note that\b/gi, 'keep in mind that')
          .replace(/\badditional\b/gi, 'more')
          .replace(/\bcomprehensive\b/gi, 'full');
        setOutput(simulated);
        setMetrics({
          aiScore: Math.floor(Math.random() * 12) + 2,
          readability: 'Medium (Grade 9)',
          flow: 'Good (Slight manual flow adjustments suggested)',
        });
      }, 800);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCopy = () => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6" id="ai-humanizer-root">
      <div className="flex flex-col gap-2">
        <h2 className="font-heading text-2xl font-black text-white tracking-tight flex items-center gap-2">
          <Sparkles className="w-6 h-6 text-indigo-400 animate-pulse" />
          <span>AI Humanizer & Detector Bypass</span>
        </h2>
        <p className="text-sm text-zinc-400">
          Transform rigid, boilerplate AI text into fluid, natural human-sounding content to safely bypass modern AI detectors (Turnitin, Copyleaks, GPTZero).
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="bg-zinc-950/60 p-5 rounded-xl border border-zinc-900 space-y-4">
          <div className="flex justify-between items-center border-b border-zinc-900 pb-2.5">
            <h3 className="text-zinc-200 text-xs font-mono font-bold uppercase tracking-wider">
              Input AI Draft Content
            </h3>
            <div className="flex gap-1.5">
              {(['standard', 'creative', 'academic', 'casual'] as const).map((m) => (
                <button
                  key={m}
                  onClick={() => setMode(m)}
                  className={`px-2.5 py-1 text-[10px] uppercase font-mono font-bold rounded transition-all cursor-pointer ${
                    mode === m
                      ? 'bg-indigo-500/15 border border-indigo-500/30 text-indigo-400'
                      : 'bg-zinc-900/50 border border-zinc-900 text-zinc-500 hover:text-zinc-300'
                  }`}
                >
                  {m}
                </button>
              ))}
            </div>
          </div>

          <div className="space-y-2">
            <textarea
              rows={12}
              value={text}
              onChange={(e) => setText(e.target.value)}
              placeholder="Paste text generated by ChatGPT, Gemini, or Claude here..."
              className="w-full bg-zinc-950/80 border border-zinc-900 text-sm font-sans text-zinc-300 rounded-lg p-3.5 focus:outline-none focus:border-indigo-500/40 focus:ring-1 focus:ring-indigo-500/20 resize-none"
            />
            <div className="flex justify-between items-center text-xs text-zinc-500">
              <span>{text.split(/\s+/).filter(Boolean).length} words</span>
              <button
                type="button"
                onClick={handleHumanize}
                disabled={isGenerating}
                className="px-4 py-2 rounded bg-indigo-600 hover:bg-indigo-500 disabled:bg-indigo-600/40 text-white font-bold font-sans transition-all flex items-center gap-1.5 cursor-pointer text-xs"
              >
                {isGenerating ? (
                  <>
                    <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                    <span>Analyzing Flow...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-3.5 h-3.5" />
                    <span>Humanize Draft</span>
                  </>
                )}
              </button>
            </div>
          </div>
        </div>

        <div className="bg-zinc-950/60 p-5 rounded-xl border border-zinc-900 flex flex-col justify-between space-y-4">
          <div className="space-y-4 flex-1">
            <div className="flex justify-between items-center border-b border-zinc-900 pb-2.5">
              <h3 className="text-zinc-200 text-xs font-mono font-bold uppercase tracking-wider">
                Humanized Content Output
              </h3>
              {output && (
                <button
                  onClick={handleCopy}
                  className="px-2.5 py-1 text-[10px] bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 text-zinc-300 rounded flex items-center gap-1 cursor-pointer"
                >
                  {copied ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                  <span>{copied ? 'Copied!' : 'Copy Code'}</span>
                </button>
              )}
            </div>

            {error && (
              <div className="p-3.5 bg-red-500/10 border border-red-500/20 rounded-lg flex gap-2 text-xs text-red-400">
                <AlertTriangle className="w-4 h-4 shrink-0" />
                <span>{error}</span>
              </div>
            )}

            {!output && !isGenerating && (
              <div className="h-64 flex flex-col items-center justify-center text-zinc-600 text-center space-y-2 border border-dashed border-zinc-900 rounded-lg">
                <ThumbsUp className="w-8 h-8 opacity-40 text-indigo-400" />
                <p className="text-xs">Provide an input draft on the left and click "Humanize Draft" to start.</p>
              </div>
            )}

            {isGenerating && (
              <div className="h-64 flex flex-col items-center justify-center text-zinc-400 text-center space-y-3">
                <div className="relative">
                  <div className="w-10 h-10 border-2 border-indigo-500/20 border-t-indigo-500 rounded-full animate-spin"></div>
                  <Sparkles className="w-4 h-4 text-indigo-400 absolute inset-0 m-auto animate-pulse" />
                </div>
                <div className="space-y-1">
                  <p className="text-xs font-mono font-bold uppercase text-indigo-400 animate-pulse">Running semantic bypass algorithms</p>
                  <p className="text-[10px] text-zinc-500 font-mono">Modulating sentence burstiness and perplexity...</p>
                </div>
              </div>
            )}

            {output && !isGenerating && (
              <div className="space-y-4">
                <div className="bg-zinc-950/90 border border-zinc-900 rounded-lg p-3.5 text-sm text-zinc-300 font-sans max-h-72 overflow-y-auto whitespace-pre-wrap selection:bg-indigo-500/20">
                  {output}
                </div>

                {metrics && (
                  <div className="grid grid-cols-3 gap-3 bg-zinc-950/80 p-3 rounded-lg border border-zinc-900 text-center">
                    <div className="space-y-1">
                      <span className="block text-[9px] font-mono font-bold text-zinc-500 uppercase tracking-widest">AI Detection Index</span>
                      <span className={`text-sm font-mono font-black ${metrics.aiScore < 10 ? 'text-emerald-400' : 'text-amber-400'}`}>
                        {metrics.aiScore}% Simulated AI
                      </span>
                    </div>
                    <div className="space-y-1 border-x border-zinc-900">
                      <span className="block text-[9px] font-mono font-bold text-zinc-500 uppercase tracking-widest">Readability Grade</span>
                      <span className="text-xs font-mono font-bold text-zinc-300">
                        {metrics.readability}
                      </span>
                    </div>
                    <div className="space-y-1">
                      <span className="block text-[9px] font-mono font-bold text-zinc-500 uppercase tracking-widest">Structural Flow</span>
                      <span className="text-xs font-mono font-bold text-indigo-400">
                        {metrics.flow}
                      </span>
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>

          <div className="flex gap-2 p-3 bg-indigo-950/10 border border-indigo-950/20 rounded-lg text-[11px] text-zinc-400">
            <Info className="w-4 h-4 text-indigo-400 shrink-0 mt-0.5" />
            <span>
              <strong>Bypass Engineering:</strong> AI text detectors spot repetitive sentence lengths, standard transitional words, and highly predictable token layouts. This tool dynamically adjusts vocabulary, introduces subtle stylistic variation, and scales flow length to replicate standard human writing patterns.
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
