import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Copy, Check, Download, FileCode, CheckCircle, ShieldAlert, Globe } from 'lucide-react';

export default function RobotsGenerator() {
  const [allowGoogle, setAllowGoogle] = useState(true);
  const [allowBing, setAllowBing] = useState(true);
  const [allowBaidu, setAllowBaidu] = useState(true);
  const [allowYandex, setAllowYandex] = useState(true);
  const [sitemapUrl, setSitemapUrl] = useState('https://example.com/sitemap.xml');
  const [customRules, setCustomRules] = useState<string>('');
  const [crawlDelay, setCrawlDelay] = useState<string>('none');
  const [copied, setCopied] = useState(false);

  const generateRobotsTxt = () => {
    let output = `# Robots.txt generated by APEX Utility Labs - 2026\n`;
    output += `User-agent: *\n`;
    
    if (crawlDelay !== 'none') {
      output += `Crawl-delay: ${crawlDelay}\n`;
    }
    
    // Googlebot
    output += `\n# Googlebot directives\nUser-agent: Googlebot\nDisallow:${allowGoogle ? '' : ' /'}\n`;
    
    // Bingbot
    output += `\n# Bingbot directives\nUser-agent: Bingbot\nDisallow:${allowBing ? '' : ' /'}\n`;

    // Baiduspider
    output += `\n# Baiduspider directives\nUser-agent: Baiduspider\nDisallow:${allowBaidu ? '' : ' /'}\n`;

    // Yandex
    output += `\n# Yandex directives\nUser-agent: Yandex\nDisallow:${allowYandex ? '' : ' /'}\n`;

    if (sitemapUrl.trim()) {
      output += `\n# Sitemap URL\nSitemap: ${sitemapUrl.trim()}\n`;
    }

    if (customRules.trim()) {
      output += `\n# Custom Directives\n${customRules.trim()}\n`;
    }

    return output;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateRobotsTxt());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([generateRobotsTxt()], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = "robots.txt";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="space-y-6" id="robots-generator-root">
      <div className="flex flex-col gap-2">
        <h2 className="font-heading text-2xl font-black text-white tracking-tight flex items-center gap-2">
          <FileCode className="w-6 h-6 text-brand" />
          <span>Robots.txt Generator & Validator</span>
        </h2>
        <p className="text-sm text-zinc-400">
          Create, customize, and validate a search-optimized robots.txt script to instruct organic search crawlers precisely.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Settings Console */}
        <div className="bg-zinc-950/60 p-5 rounded-xl border border-zinc-900 space-y-6">
          <h3 className="text-zinc-200 text-sm font-bold uppercase tracking-wider font-heading border-b border-zinc-900 pb-2">
            Crawler Settings
          </h3>

          {/* Crawler direct toggle options */}
          <div className="space-y-4">
            <div className="flex items-center justify-between p-3 rounded-lg bg-zinc-900/40 border border-zinc-900">
              <div className="flex flex-col">
                <span className="text-xs font-bold text-zinc-200 font-heading">Googlebot</span>
                <span className="text-[10px] text-zinc-500 font-mono">Allow Google Search spider to index your pages</span>
              </div>
              <button
                onClick={() => setAllowGoogle(!allowGoogle)}
                className={`px-3 py-1 text-[11px] font-bold rounded-md font-sans border transition-all ${
                  allowGoogle 
                    ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400' 
                    : 'bg-red-500/10 border-red-500/30 text-red-500'
                }`}
              >
                {allowGoogle ? 'ALLOWED' : 'DISALLOWED'}
              </button>
            </div>

            <div className="flex items-center justify-between p-3 rounded-lg bg-zinc-900/40 border border-zinc-900">
              <div className="flex flex-col">
                <span className="text-xs font-bold text-zinc-200 font-heading">Bingbot</span>
                <span className="text-[10px] text-zinc-500 font-mono">Allow Bing Search crawler index authorization</span>
              </div>
              <button
                onClick={() => setAllowBing(!allowBing)}
                className={`px-3 py-1 text-[11px] font-bold rounded-md font-sans border transition-all ${
                  allowBing 
                    ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400' 
                    : 'bg-red-500/10 border-red-500/30 text-red-500'
                }`}
              >
                {allowBing ? 'ALLOWED' : 'DISALLOWED'}
              </button>
            </div>

            <div className="flex items-center justify-between p-3 rounded-lg bg-zinc-900/40 border border-zinc-900">
              <div className="flex flex-col">
                <span className="text-xs font-bold text-zinc-200 font-heading">Baiduspider</span>
                <span className="text-[10px] text-zinc-500 font-mono">Allow China's major search engine spider to index</span>
              </div>
              <button
                onClick={() => setAllowBaidu(!allowBaidu)}
                className={`px-3 py-1 text-[11px] font-bold rounded-md font-sans border transition-all ${
                  allowBaidu 
                    ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400' 
                    : 'bg-red-500/10 border-red-500/30 text-red-500'
                }`}
              >
                {allowBaidu ? 'ALLOWED' : 'DISALLOWED'}
              </button>
            </div>


          </div>

          <div className="space-y-2">
            <label className="block text-[10px] font-mono text-zinc-400 uppercase tracking-widest leading-none">
              Sitemap XML Path
            </label>
            <input
              type="url"
              value={sitemapUrl}
              onChange={(e) => setSitemapUrl(e.target.value)}
              placeholder="e.g. https://yourdomain.com/sitemap.xml"
              className="w-full bg-zinc-950/80 border border-zinc-900 text-sm font-mono text-zinc-300 rounded px-3 py-2.5 focus:outline-none focus:border-brand/45"
            />
          </div>

          <div className="space-y-2">
            <label className="block text-[10px] font-mono text-zinc-400 uppercase tracking-widest leading-none">
              Crawl Delay Option
            </label>
            <select
              value={crawlDelay}
              onChange={(e) => setCrawlDelay(e.target.value)}
              className="w-full bg-zinc-950/80 border border-zinc-900 text-sm font-sans text-zinc-300 rounded px-3 py-2.5 focus:outline-none focus:border-brand/45"
            >
              <option value="none">No Delay (Recommended)</option>
              <option value="5">5 Seconds Delay</option>
              <option value="10">10 Seconds Delay</option>
              <option value="20">20 Seconds Delay</option>
            </select>
          </div>

          <div className="space-y-2">
            <label className="block text-[10px] font-mono text-zinc-400 uppercase tracking-widest leading-none">
              Custom Directives (Optional)
            </label>
            <textarea
              rows={3}
              value={customRules}
              onChange={(e) => setCustomRules(e.target.value)}
              placeholder="e.g. Disallow: /private-folder/&#10;Allow: /public-images/"
              className="w-full bg-zinc-950/80 border border-zinc-900 text-xs font-mono text-zinc-300 rounded p-3 focus:outline-none focus:border-brand/45"
            />
          </div>
        </div>

        {/* Real-time Code Output & Validation Screen */}
        <div className="bg-zinc-950/60 p-5 rounded-xl border border-zinc-900 flex flex-col justify-between space-y-4">
          <div className="space-y-3">
            <div className="flex items-center justify-between pb-2 border-b border-zinc-900">
              <h3 className="text-zinc-200 text-sm font-bold uppercase tracking-wider font-heading">
                Generated robots.txt Preview
              </h3>

              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={handleCopy}
                  className="px-2 py-1.5 rounded bg-zinc-900 border border-zinc-800 text-zinc-400 hover:text-brand transition-all flex items-center gap-1.5 text-xs font-mono cursor-pointer"
                  title="Copy robots.txt code to Clipboard"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-brand" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copied ? 'Copied' : 'Copy'}</span>
                </button>

                <button
                  type="button"
                  onClick={handleDownload}
                  className="px-2 py-1.5 rounded bg-zinc-900 border border-zinc-800 text-zinc-400 hover:text-brand transition-all flex items-center gap-1.5 text-xs font-mono cursor-pointer"
                  title="Download file directly"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download</span>
                </button>
              </div>
            </div>

            <pre className="p-4 rounded-lg bg-zinc-950 border border-zinc-900 text-xs font-mono text-emerald-400 overflow-x-auto select-all max-h-[350px]">
              {generateRobotsTxt()}
            </pre>
          </div>

          {/* Verification / Security Status Indicators */}
          <div className="p-3.5 rounded-lg bg-zinc-900/30 border border-zinc-900/60 flex items-start gap-3">
            <CheckCircle className="w-5 h-5 text-emerald-400 shrink-0 mt-0.5" />
            <div className="space-y-1">
              <p className="text-xs font-bold text-zinc-200 font-heading">Sitemap Syntax Validated</p>
              <p className="text-[10px] text-zinc-500 leading-tight">
                Your generated Robots.txt has been audited for sitemap declarations and crawler compatibility. It conforms strictly to standard search engine schema requirements.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
