import { ActiveTab } from './types';

export const SEO_H1_MAPPING: Record<ActiveTab, string> = {
  dashboard: 'Apex Developer & SEO Utility Suite',
  'compress-pdf': 'Free Online PDF Compressor - Reduce PDF Size',
  'webp-converter': 'Free WebP Converter Online - Convert WebP to JPG/PNG',
  'json-beautifier': 'Free Online JSON Beautifier & Schema Validator',
  'sitemap-seo': 'Free Sitemap SEO Audit Tool - Analyze Sitemap Online',
  'sitemap-generator': 'Free XML Sitemap Generator Online - Create Sitemap for Google',
  'image-to-pdf': 'Free Image to PDF Converter Online - JPG/PNG to PDF',
  'join-pdf': 'Free PDF Merger Online - Combine PDF Files',
  'ai-writer': 'Free AI Writer Online - Premium AI Copywriting Assistant',
  'password-generator': 'Free Secure Password Generator - Generate Safe Passwords',
  'qr-generator': 'Free QR Code Generator Online - Create High-Res QR Codes',
  'unit-converter': 'Free Online Unit Converter - Easy Measurement Conversions',
  'svg-rasterizer': 'Free SVG to PNG/JPEG Rasterizer - High-Res SVG Converter',
  'batch-processor': 'Free Batch Image Processor Online - Bulk Crop & Resize',
  'json-diff': 'Free JSON Diff Checker Online - Compare Two JSON Files',
  'secure-hash': 'Free Secure Hash Generator Online - MD5, SHA-256, SHA-512',
  'color-palette': 'Free Color Palette Generator - Hex Code Color Schemes',
  'digital-signature': 'Free Digital Signature Generator Online - Sign PDF Documents',
  'seo-optimizer': 'Free SEO Analyzer & Page Speed Optimizer Tool',
  'base64-converter': 'Free Base64 Encoder & Decoder Online - String to Base64',
  'regex-tester': 'Free Online Regex Tester & Regular Expression Debugger',
  'csv-json-converter': 'Free CSV to JSON Converter Online - CSV & JSON Formatting',
  'image-compressor': 'Free Online Image Compressor - Compress JPEG, PNG & WebP',
  'quick-image-optimizer': 'Free Quick Image Optimizer - Instantly Optimize Web Graphics',
  'rich-text-stats': 'Free Rich Text Statistics Tool - Word & Character Counter',
  'audio-trimmer': 'Free Online Audio Trimmer - Cut & Edit Audio Files',
  'ai-transcriber': 'Free AI Audio Transcriber - Speech to Text Online',
  'pdf-analyst': 'Free PDF Analyst & Document Inspector Online',
  'exif-stripper': 'Free EXIF Metadata Stripper - Remove Image Metadata',
  'image-vectorizer': 'Free Image Vectorizer - PNG/JPG to SVG Converter',
  'code-snapshot': 'Free Code Snapshot Maker - Create Elegant Code Screenshots',
  'private-sketchpad': 'Free Online Sketchpad & Vector Drawing Board',
  'case-converter': 'Free Case Converter Online - UPPERCASE, lowercase, Title Case',
  'lorem-generator': 'Free Lorem Ipsum Generator - Placeholder Text Creator',
  'image-cropper': 'Free Image Cropper Online - Crop JPG, PNG, GIF, WebP',
  'date-calculator': 'Free Date Calculator - Add/Subtract Days & Calculate Duration',
  'seo-inspect': 'Free SEO Inspector & Webpage Audit Tool',
  'privacy-policy': 'Privacy Policy - 100% Offline and Private Security',
  'terms-of-service': 'Terms of Service - Open-Source Web Utility Sandbox',
  'about-us': 'About Apex Utility Labs - Premium Secure Tools Suite',
  guides: 'Developer & Creator Guides - Online Productivity Tutorials',
  'content-planner': 'Free Content Planner & Editorial Calendar Tool',
  'schema-generator': 'Free Schema Markup Generator - Structured Data Creator',
  'content-gap': 'Free SEO Competitor Gap Analyzer - Keyword Gap Finder',
  'keyword-cluster': 'Free AI Keyword Cluster Tool - Group Keywords for SEO',
  'css-generator': 'Free CSS Glassmorphism & Box Shadow Generator',
  'robots-txt': 'Free Robots.txt Generator & Validator Tool',
  'dns-lookup': 'Free DNS Lookup & Domain Records Analyzer',
  'user-agent': 'Free User-Agent Parser Online - Deconstruct Browser Client Strings',
  'html-markdown': 'Free HTML to Markdown Converter - Markdown Syntax Generator',
  'meta-tags': 'Free Meta Tags Generator & Social Preview Optimizer',
  'ai-humanizer': 'Free AI Humanizer - Convert AI Text to Human Style',
  'tone-analyzer': 'Free Tone Analyzer Online - AI Text Emotion Checker',
  'resume-optimizer': 'Free AI Resume Optimizer & ATS Checker',
  'text-summarizer': 'Free AI Text Summarizer - Article & PDF Summarizer',
  'passport-photo': 'Free Passport Photo Maker - Crop & Print Passport Photos',
  'meme-generator': 'Free Meme Generator Online - Create Custom Memes',
  'headshot-generator': 'Free AI Headshot Generator Online',
  'image-upscaler': 'Free AI Image Upscaler - Enlarge Images without Quality Loss',
  'mockup-generator': 'Free Mockup Generator - Product & Device Layout Maker',
  'pdf-converter': 'Free PDF Converter Online - Word/Excel/PPT to PDF & Back',
  'pdf-form-filler': 'Free PDF Form Filler - Fill out PDF Forms Online',
  'pdf-signer': 'Free PDF Signer Online - Draw & Place Electronic Signatures',
  'uuid-generator': 'Free UUID Generator Online - Create V1, V3, V4, V5 UUIDs',
  'cron-builder': 'Free Cron Expression Builder & Cronjob Generator',
  'jwt-decoder': 'Free JWT Decoder Online - Parse and Inspect JSON Web Tokens',
  'favicon-generator': 'Free Favicon Generator Online - Create ICO & PNG Favicons',
  'gradient-generator': 'Free CSS Gradient Generator - Multi-color Gradients',
  'password-sharer': 'Free Password Sharer - Share Secrets and Credentials Securely',
  'data-breach': 'Free Data Breach Checker - Check Leaked Passwords and Emails',
  'checksum-verifier': 'Free Checksum Verifier Online - Verify File SHA-256 and MD5',
  'age-calculator': 'Free Age Calculator - Calculate Your Exact Age',
  'loan-calculator': 'Free Loan Calculator - Monthly Mortgage Payment & Interest',
  'bmi-calculator': 'Free BMI Calculator - Check Body Mass Index Online',
  'video-recorder': 'Free Online Video Recorder & Screen Capturer',
  'screen-recorder': 'Free Online Screen Recorder',
  'webcam-recorder': 'Free Webcam Recorder Online',
  'voice-recorder': 'Free Online Voice Recorder',
  'video-compressor': 'Free Online Video Compressor',
  'video-resizer': 'Resize Video Online Free',
  'video-cutter': 'Cut Video Online Free',
  'mute-video': 'Remove Audio from MP4 Online',
  'video-speed': 'Change Video Speed Online',
  'video-rotator': 'Rotate Video 90 Degrees Online Free',
  'video-merger': 'Video Merger Free',
  'video-converter': 'Free Online Video Converter',
  'video-to-gif': 'Video to GIF Maker',
  'video-to-mp3': 'Extract Audio from Video Online',
  'audio-converter': 'Audio Format Converter',
  'subtitle-converter': 'SRT to VTT Subtitle Converter Online',
  'microphone-tester': 'Free Online Microphone Tester',
  'webcam-check': 'Free Webcam Check Online',
  'speaker-tester': 'Free Speaker Test Online',
};

export const SEO_DESC_MAPPING: Partial<Record<ActiveTab, string>> = {
  'screen-recorder': 'Online screen and audio recorder with no watermark – how to screen record on Chrome without extensions or lag.',
  'webcam-recorder': 'Record raw high-definition video from connected cameras with synchronized microphone streams and zero lag.',
  'voice-recorder': 'Browser voice recorder with live audio visualizer – record raw mic voice streams and export WAV files offline.',
  'video-compressor': 'Compress video online free with zero watermark. Set quality targets or compression ratios to easily fit files for Discord under 25MB.',
  'video-resizer': 'Convert 16:9 videos to 9:16 vertical format online free. Easily crop videos for TikTok, Instagram Reels, and YouTube Shorts.',
  'video-cutter': 'Trim video clips and cut segments online completely locally. High-precision video trimmer with timeline crop controls.',
  'mute-video': 'Mute videos and remove audio tracks from MP4, WebM, and MKV files online free. Clean soundless clips processed entirely offline.',
  'video-speed': 'Fast and slow motion video speed controller. Adjust playback speeds easily from slow 0.25x up to fast 4.0x.',
  'video-rotator': 'Rotate and flip video clips 90, 180, or 270 degrees clockwise. Fix upside-down smartphone video orientations instantly.',
  'video-merger': 'Combine multiple video clips into one file. Drag, order, and join video segments offline with premium export quality.',
  'video-converter': 'Convert WebM to MP4 online free or transcode MOV to MP4, MKV, or other container formats safely in your browser.',
  'video-to-gif': 'Turn video clips into looping GIFs online. Control resolution widths, frame rate buffers, and palette dither strategies.',
  'video-to-mp3': 'Convert video to MP3 high bitrate online. Cleanly extract and download raw sound tracks from MP4 or WebM files.',
  'audio-converter': 'Transcode MP3, WAV, OGG, and M4A audio formats offline. Convert sampling rates and containers instantly.',
  'subtitle-converter': 'Convert SRT subtitle tracks into standard WebVTT (VTT) or vice-versa with automated timeline adjustments.',
  'microphone-tester': 'Mic tester for Google Meet and Zoom with playback loopback and live decibel level charts.',
  'webcam-check': 'Check webcam resolution, aspect ratios, and camera lighting online with zero watermark.',
  'speaker-tester': 'Stereo speaker test left right channel sound, balance sweeps, and custom frequency sweeps.',
};
