export type ActiveTab =
  | 'dashboard'
  | 'compress-pdf'
  | 'webp-converter'
  | 'json-beautifier'
  | 'sitemap-seo'
  | 'sitemap-generator'
  | 'image-to-pdf'
  | 'join-pdf'
  | 'ai-writer'
  | 'password-generator'
  | 'qr-generator'
  | 'unit-converter'
  | 'svg-rasterizer'
  | 'batch-processor'
  | 'json-diff'
  | 'secure-hash'
  | 'color-palette'
  | 'digital-signature'
  | 'seo-optimizer'
  | 'base64-converter'
  | 'regex-tester'
  | 'csv-json-converter'
  | 'image-compressor'
  | 'quick-image-optimizer'
  | 'rich-text-stats'
  | 'audio-trimmer'
  | 'ai-transcriber'
  | 'pdf-analyst'
  | 'exif-stripper'
  | 'video-recorder'
  | 'image-vectorizer'
  | 'code-snapshot'
  | 'private-sketchpad'
  | 'case-converter'
  | 'lorem-generator'
  | 'image-cropper'
  | 'date-calculator'
  | 'seo-inspect'
  | 'privacy-policy'
  | 'terms-of-service'
  | 'about-us'
  | 'guides'
  | 'content-planner'
  | 'schema-generator'
  | 'content-gap'
  | 'keyword-cluster'
  | 'css-generator'
  | 'robots-txt'
  | 'dns-lookup'
  | 'user-agent'
  | 'html-markdown'
  | 'meta-tags';

export interface JSONBeautifierState {
  rawInput: string;
  beautifiedOutput: string;
  tabSize: number | string;
  isValid: boolean | null;
  errorMessage: string | null;
}

